// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6zLfiNLjWOqdapmgrUhuTXkfZ0VdsIhA',
    appId: '1:116724370672:web:f9cadc3777f053cb52c635',
    messagingSenderId: '116724370672',
    projectId: 'shipconvenient-24bb1',
    authDomain: 'shipconvenient-24bb1.firebaseapp.com',
    storageBucket: 'shipconvenient-24bb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH6U5SCgYeOX7s3QxTgbBMV4xsuz_5wlw',
    appId: '1:116724370672:android:ee6bf4591282726e52c635',
    messagingSenderId: '116724370672',
    projectId: 'shipconvenient-24bb1',
    storageBucket: 'shipconvenient-24bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOlfBPoQvatt9ydYT65Cax7NEYqpAxct8',
    appId: '1:116724370672:ios:6d35665d12b29d8652c635',
    messagingSenderId: '116724370672',
    projectId: 'shipconvenient-24bb1',
    storageBucket: 'shipconvenient-24bb1.appspot.com',
    iosClientId: '116724370672-4ki8jgk2cbau0e6755lqbardtjto79nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shipconvenient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOlfBPoQvatt9ydYT65Cax7NEYqpAxct8',
    appId: '1:116724370672:ios:6d35665d12b29d8652c635',
    messagingSenderId: '116724370672',
    projectId: 'shipconvenient-24bb1',
    storageBucket: 'shipconvenient-24bb1.appspot.com',
    iosClientId: '116724370672-4ki8jgk2cbau0e6755lqbardtjto79nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.shipconvenient',
  );
}
